name: ancestreegp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - networkx
  - altair
  - pydot
  - pandas
  - numpy
  - graphviz
  - pygraphviz
  - pip
  - pip:
      - nx_altair